Stories
742th/raklechitsya pull request #10
Opened 2020-05-12 07:25 UTC by Metanka

Верстка на 1440 без переключения кнопок снизу и футера

2020-05-12 12:55 UTC, 742th requested changes

2020-05-12 12:55 UTC, 742th commented on components/UI/BtnSearch.vue
> +</style>
Убери btnsearch, и возьми готовую кнопку ButtonForm, у меня инпут готов, но тебе нужно под себя в него занести стили

2020-05-12 15:02 UTC, ninanazarova requested changes

2020-05-12 15:02 UTC, ninanazarova commented on pages/stories.vue
> +<template>
Этот файл нужно переименовать в index.vue и положить по такому пути pages/stories/index.vue

https://nuxtjs.org/guide/routing/

2020-05-13 09:45 UTC, 742th approved these changes
Мержим

2020-05-13 09:47 UTC, ninanazarova approved these changes

2020-05-13 09:48 UTC, merged