Закончил страницу показа истории, пока без адаптива
742th/raklechitsya pull request #13
Opened 2020-05-12 19:17 UTC by EvgeniyPanin

2020-05-12 19:19 UTC, EvgeniyPanin commented
Залез чуток в глобальные стили FormButton, они мешались при импорте. Если где то что то сместилось, нужно поправить локально

2020-05-13 08:21 UTC, 742th requested changes

2020-05-13 08:21 UTC, 742th commented on components/UI/ButtonForm.vue
>    line-height: 19px;
Не Жень, смотри, когда берешь компонент, и тебе локально нужно что-то изменить, ты локально это и меняешь, т.е по дефолту в большинстве у кнопки одни ширина, а тебе нужна другая, то меняй ее у себя в блоке

2020-05-13 09:03 UTC, EvgeniyPanin commented on components/UI/ButtonForm.vue
>    line-height: 19px;
ок, просто это не очень удобно. приходится лезть смотреть какое свойство в дефолте, и именно его перезатирать, например если в дефолте стоит max-width 226px; то когда я указываю локально width 100% у себя в элементе, оно не применится, мне нужно будет у себя указать именно max-width, сумятица вносится.

2020-05-13 10:08 UTC, 742th approved these changes
Мерж

2020-05-13 10:08 UTC, merged