Develop footer
742th/raklechitsya pull request #4
Opened 2020-05-08 19:26 UTC by roschek

2020-05-08 22:52 UTC, 742th commented
Тебе нужно сначала конфликт разрулить, как писала Алина

2020-05-09 17:41 UTC, 742th requested changes

2020-05-09 17:41 UTC, 742th commented on components/Footer.vue
> +.footer {
Нужен марджин как по макету, нужно задать цвет бекграунда

2020-05-09 17:41 UTC, 742th commented on components/Footer.vue
> +          <p class="footer__add">Поделитесь <span>&#129125;</span></p>
Стрелку можно попробовать вставить из фигмы, скопировав ее из текста, чтоб выглядело по макету

2020-05-09 17:41 UTC, 742th commented on components/Footer.vue
> +  font-size: 32px;
Посмотреть расстояние между элементами по макету

2020-05-09 17:41 UTC, 742th commented on components/Footer.vue
> +          <a href="#" class="footer__social-link">Youtube</a>
Весь блок с ссылками походу уберут сегодня, и в макете будет только кнопка "поделись" которая будет вызывать попап со всеми нужными им ссылками. Лучше оставить сразу тогда "поделись", и сделать его кнопкой, в ui есть компонент кнопки которую я сделал, ее можно использовать - buttonForm называется.

2020-05-09 17:41 UTC, 742th commented on components/Footer.vue
> +          <a href="#" class="footer__social-link">Youtube</a>
Сам попап допилим потом, как будет больше информации

2020-05-09 18:03 UTC, roschek commented
вроде все поправил, должно работать

2020-05-09 19:22 UTC, 742th requested changes

2020-05-09 19:22 UTC, 742th commented on Footer.vue
> +        </nav>
В целом все выглядит норм! 
Еще раз проверить отступы между "Спасибо за ..." и "Главная" , у меня показывает между ними расстояние больше чем в задано в макете. И добавь на весь футер цвет как в макете, в дефолте нет цвета, и в каждом блоке мы задаем его сами.  (скрин верстки, не макета)
![изображение](https://user-images.githubusercontent.com/53303887/81482960-45384080-9243-11ea-8096-000e7b9f565a.png)

2020-05-09 19:25 UTC, 742th commented on Footer.vue
> +        </nav>
Просто падингом подвинуть и все 
![изображение](https://user-images.githubusercontent.com/53303887/81483049-fccd5280-9243-11ea-8ff0-ec1e60b0d1d7.png)

2020-05-11 18:14 UTC, 742th commented
Реши конфликты

2020-05-11 18:33 UTC, roschek commented
Странно, не вижу конфликтов

2020-05-11 18:39 UTC, 742th commented
![изображение](https://user-images.githubusercontent.com/53303887/81598425-f1a72d80-93cf-11ea-8b14-739211f5a8af.png)

2020-05-11 22:49 UTC, 742th requested changes
Внимательней прочитай замечания. Для наглядности привел скриншоты из фигмы и твою реализацию.

2020-05-11 22:49 UTC, 742th commented on components/Footer.vue
> +  margin-top: 60px;
Не ленись и напиши нормальные марджины, без вот этих вот выкрутасов с отрицательным значением. В целом все хорошо, прошу обратить твое пристальное внимание на 1) Все те же несчастные Главная и История (в фигме есть штука как Rulers, она находится в правом верхнем углу, включи ее, и так тебе будет наглядней чтоле) В макете  Истории четко находятся под Фонд Хабенского.
![изображение](https://user-images.githubusercontent.com/53303887/81619422-3f349200-93f2-11ea-9aad-669ce5670103.png)
 2) Обрати внимание на студенты яндекса и youtube, они на разном расстоянии, думаю с этим можешь не возиться, но удивляет невнимательность к макету
![изображение](https://user-images.githubusercontent.com/53303887/81619464-54a9bc00-93f2-11ea-9ad1-ebbe9aac39ae.png) 
Твой вариант в вертске: 
![изображение](https://user-images.githubusercontent.com/53303887/81619513-73a84e00-93f2-11ea-830e-4c44547ec2fc.png)

2020-05-11 22:55 UTC, 742th commented on components/Footer.vue
> +  margin-top: 60px;
Прошу успеть сделать это до среды, т.е получается сегодня. Так как нужно будет показать уже готовый экземпляр индекс страницы.

2020-05-11 23:20 UTC, 742th commented on components/Footer.vue
> +  margin-top: 60px;
Еще нашел у тебя лишний пробел, сам не понимаю откуда он взялся, но даже в инспекторе он пишет, что есть пробел.
Порылся в инете, если задать ссылкам `display: block` то этот пробел пропадет. 
![изображение](https://user-images.githubusercontent.com/53303887/81621261-a05e6480-93f6-11ea-9f64-34c1ca867fad.png)

2020-05-11 23:21 UTC, 742th commented on components/Footer.vue
> +  margin-top: 60px;
Правда потом нужно в футер меню` display: flex` сделать, ну думаю с этим ты справишься

2020-05-13 21:31 UTC, 742th approved these changes

2020-05-13 21:31 UTC, merged