instagram section 768-1440px responsive layout - done. Instagram vidgets data hadn't been added
742th/raklechitsya pull request #9
Opened 2020-05-10 15:20 UTC by EvgeniyPanin

2020-05-10 15:55 UTC, EvgeniyPanin commented
Заголовок с хэштэгом писать не стал, думаю переиспользовать компонент из блока с видео. на загвоздка в том, что там он не является заголовком, а в инстаграмме думаю должен являться, что думаете?

2020-05-10 17:42 UTC, 742th commented
Я думаю что нужно блок до конца добить и мержить, бери готовый компонент. 
Мы по возможности делаем блоки до конца, если уж совсем нет чего-то непонятного

2020-05-10 17:43 UTC, 742th commented
+ реши конфликты

2020-05-11 22:05 UTC, 742th requested changes

2020-05-11 22:05 UTC, 742th commented on components/UI/hash.vue
> +</script>
тэг используется всего два раза на сайте. Смысла конкретно в этом компоненте нет, но можешь оставить. Нужно использовать компонент который я уже сделал называется Banner.

2020-05-11 22:05 UTC, 742th commented on components/UI/InstagramBanner.vue
> +</template>
Не вижу смысла в этом компоненте когда уже есть готовый Banner, используй его.

2020-05-11 22:05 UTC, 742th commented on components/UI/instagramCard.vue
> +      alt="instagram"
Лучше src сделать пропсой, скорее всего карточки будут динамически получены из сервера, можешь сразу сделать или оставить, как тебе удобно.

2020-05-11 22:05 UTC, 742th commented on components/blocks/InstagramSection.vue
> +          </p>
Для этой штуки есть готовый компонент, называется QuoteParagraph, используй его.

2020-05-11 22:05 UTC, 742th commented on components/blocks/InstagramSection.vue
> +          <instagram-card></instagram-card>
В целом все отлично за исключением пары моментов, поправь их и все.
Как будешь исправлять, заодно посмотри чтоб карточки потом в два ряда становились, это уже есть в фигме.
Думаю нужно чтоб они пораньше становились в два ряда, а не в 320px, где нибудь на 470px мб. Или опять же на твое усмотрение, можешь на глаз сам понять когда нужен брейкпоинт для перелома карточек.

2020-05-12 10:12 UTC, 742th approved these changes
Отлично!

2020-05-12 10:12 UTC, merged